{% set version = "0.5.1" %}

package:
  name: jupyterlite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlite/jupyterlite-{{ version }}.tar.gz
  sha256: a2e618dbe223d254edf7a04916356b5ff15b88cf514401a7913c8853154fc43b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.6.3,<2
    - pip
    - python {{ python_min }}
  run:
    - jupyterlite-core {{ version }}
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyterlite
  commands:
    - pip check
    - jupyter lite --version
    - jupyter lite --help

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: JupyterLite metapackage
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://jupyterlite.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
