{% set version = "0.5.0" %}
{% set core_version = ">=" ~ version ~ ",<0.5.0" %}
{% set python_min = python_min | default("3.9") %}

package:
  name: jupyterlite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlite/jupyterlite-{{ version }}.tar.gz
  sha256: 8f0415cad2864d5bad0d1fb247c7deec466b003c57c4b5503276f6ff37e551f7

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.6.3,<2
    - pip
    - python {{ python_min }}
  run:
    - jupyterlite-core {{ core_version }}
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyterlite
  commands:
    - pip check
    - jupyter lite --version
    - jupyter lite --help

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: JupyterLite metapackage
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://jupyterlite.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
