# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1


context:
  version: "0.6.2"

package:
  name: jupyterlite
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlite/jupyterlite-${{ version }}.tar.gz
  sha256: 0caed5531e1c25dabf335aad78d6979998a0e5505228bfe618fdf96aeb067f75

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.6.3,<2
    - pip
    - python ${{ python_min }}.*
  run:
    - jupyterlite-core ${{ version }}.*
    - python >=${{ python_min }}

tests:
  - python:
      imports: jupyterlite
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - jupyter lite --version
      - jupyter lite --help

about:
  summary: JupyterLite metapackage
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/jupyterlite/jupyterlite
  documentation: https://jupyterlite.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
